### ISSUE TITLE
sh artifact with wrong url shown as Deployed

### ISSUE THREAD

**Issue by jurajcik** [tuwiendsg/SALSA#32]
If an ArtifactReference has a nonexistent url SALSA shows it as DEPLOYED. This is definitely a bug. Here is an example: 
http://128.130.172.215/salsa/upload/files/juraj/issues/mela_tosca_error.xml

**Comment by leduchung** [comment]
This is a bug. Added a checking for successful download artifacts and return error state if fail: bbbc2956fc6cb6d2ca32ff9631e87b78d24a18a0
